name: "Build Armbian"
on:
  workflow_dispatch:
  push:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    strategy:
            matrix:
                image: [
                        orangepi3b,
                        orangepizero2,
                        orangepizero,
                        # rpi4b, # TODO: failing for now, we just use the latest image from Arbian
                        ]
                ubuntu: [
                        # focal,
                        jammy,
                        # noble
                        ]
                version: ["v25.02"]
                branch: ["edge", "current", "legacy", "vendor"]
                exclude:
                    - image: orangepizero
                      branch: vendor
                    - image: orangepizero2
                      branch: vendor
                    - image: orangepizero2
                      branch: legacy
                    - image: orangepi3b
                      branch: current
                    - image: orangepi3b
                      branch: legacy
            fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   ${{ matrix.ubuntu }}                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     ${{ matrix.image }}                   # build target
          armbian_branch:    ${{ matrix.version }}                  # branch
          armbian_kernel_branch: ${{ matrix.branch }}                  # kernel branch
      # if on tag, upload to github release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/output/images/*.img*.xz
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref }}
          release_notes: ${{ github.ref }}
          draft: false
          prerelease: false
  join_shasums:
    runs-on: ubuntu-latest
    # needs: build-armbian
    # if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # install gh
      - name: Install gh
        run: |
          sudo apt-get update
          sudo apt-get install gh
      # login to gh
      - name: Login to gh
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      # download all .sha files of the last release
      - name: Download SHA files
        run: |
          mkdir -p shasums
            gh release download --pattern '*.sha' --dir shasums
      # remove */armbian/.tmp/image-165daace-3671-4e2d-b904-2cbce039a433/ from the file names, keeping the checksum and the actual filename
      - name: Remove tmp path from file names
        run: |
          echo "cleaning up..."
          for file in shasums/*.sha; do
            sed -i 's|\*/armbian/.tmp/image-[0-9a-f-]*/||g' $file
          done
          # sed -i 's|\*/armbian/.tmp/image-[0-9a-f-]*/||g' *.sha
      - name: Upload all_shasums.sha256sum
        run: |
          cd shasums
          ls
          # get latest release tag
          latest_tag=$(gh release list --limit 1 | awk '{print $4}')

          gh release upload $latest_tag *.sha --clobber