name: "Build Armbian"
on:
  workflow_dispatch:
  push:
jobs:
  build-armbian-main:
    runs-on: ubuntu-latest
    steps:
      - uses: arendjan/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "bananapim5"                   # build target
  build-armbian-fixed:
    runs-on: ubuntu-latest
    steps:
      - uses: arendjan/build@fix-action-no-custom-userpatches
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "bananapim5"                   # build target