name: "Build Armbian"
on:
  workflow_dispatch:
  push:
jobs:
  build-armbian:
    strategy:
            matrix:
                source: [
                        main,
                        fix-action-no-custom-userpatches
                        ]
    runs-on: ubuntu-latest
    steps:
      - uses: arendjan/build@${{ matrix.source }}
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "bananapim5"                   # build target
